version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=12345678
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=34z27894782974823748902374827489327432658293743
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=postgres
    volumes:
      - postgres-db:/var/lib/postgresql/
volumes:
  postgres-db:
